config/routes.rb
Rails.application.routes.draw do
  resources :books do
    member do
      get :delete
    end
  end

  root 'books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, :price, :author, :published, :publisher, :release_date, :pages, presence: true
  validates :price, numericality: { greater_than: 0 }
  validates :title, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy delete ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # GET /books/1/delete
  def delete
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully deleted." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :price, :author, :published, :publisher, :release_date, :pages)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def formatted_date(date)
    if date.present?
      date.strftime("%B %e, %Y")
    else
      "No Date Available"
    end
  end

  def get_field(book, field)
    if book.public_send(field).present?
      book.public_send(field)
    else
      "#{field.to_s.titleize} Unknown"
    end
  end
end

app/views/books/_alert.html.erb
<% if content_for?(:alert_content) %>
  <div class="alert <%= defined?(alert_type) ?  alert_type : 'alert-success' %>" role="alert">
    <%= yield :alert_content %>
  </div>
<% end %>

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <h3>
    <i class="bi bi-book me-2"></i>
    <strong>
      <%= book.title %>
    </strong>
  </h3>
  <table class="table">
    <tbody>
    <tr>
      <th scope="row">Author</th>
      <td><%= get_field(book, 'author') %></td>
    </tr>
    <tr>
      <th scope="row">Price</th>
      <td><%= number_to_currency book.price %></td>
    </tr>
    <tr>
      <th scope="row">Publisher</th>
      <td><%= get_field(book, 'publisher') %></td>
    </tr>
    <tr>
      <th scope="row">Published</th>
      <td><%= formatted_date(book.published) %></td>
    </tr>
    <tr>
      <th scope="row">Released On</th>
      <td><%= formatted_date(book.release_date) %></td>
    </tr>
    <tr>
      <th scope="row">Pages</th>
      <td><%= get_field(book, 'pages') %></td>
    </tr>
    </tbody>
  </table>
</div>

app/views/books/_breadcrumb.html.erb
<hr />
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <% breadcrumbs.each_with_index do |breadcrumb, index| %>
      <li class="breadcrumb-item <%= 'active' if index == breadcrumbs.length - 1 %>" aria-current="page">
        <% if index == breadcrumbs.length - 1 %>
          <%= breadcrumb[:name] %>
        <% else %>
          <%= link_to(breadcrumb[:name], breadcrumb[:path]) %>
        <% end %>
      </li>
    <% end %>
  </ol>
</nav>
<hr />

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% content_for :alert_content do %>
    <% if book.errors.any? %>
      <h4><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h4>
      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    <% end %>
  <% end %>

  <%= render("alert", alert_type: "alert-danger") %>

  <div class="mb-3">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :author %>
    <%= form.text_field :author, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :price %>
    <%= form.number_field :price, step: 0.01, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :published %>
    <%= form.date_field :published, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :publisher %>
    <%= form.text_field :publisher, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :release_date %>
    <%= form.date_field :release_date, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :pages %>
    <%= form.number_field :pages, step: 1, class: 'form-control' %>
  </div>

  <%= form.submit class: 'btn btn-primary' %>
<% end %>

app/views/books/delete.html.erb
<h1>Delete Book</h1>

<%= render("breadcrumb", breadcrumbs: [
  { name: "Books", path: root_path },
  { name: @book.title, path: @book },
  { name: "Delete" }
]) %>


<div class="card">
  <div class="card-body">
    <p>
      Are you sure you want to delete the book "<strong><%= @book.title %></strong>"?
    </p>

    <div class="d-flex flex-row gap-3 mt-3">
      <%= link_to("Go Back", :back, class: "btn btn-secondary") %>
      <%= button_to("Delete", @book, method: :delete, class: "btn btn-danger") %>
    </div>
  </div>
</div>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render("breadcrumb", breadcrumbs: [
  { name: "Books", path: root_path },
  { name: @book.title, path: @book },
  { name: "Edit" }
]) %>

<div class="card">
  <div class="card-body">
    <%= render("form", book: @book) %>
  </div>
</div>

app/views/books/index.html.erb
<h1>Books</h1>

<% content_for :alert_content do %>
  <% notice %>
<% end %>

<%= render("alert") %>

<div class="card">
  <div class="card-body">
    <% if @books.present? %>
      <div id="books">
        <table class="table">
          <thead>
            <tr>
              <th></th>
              <th scope="col">Title</th>
              <th scope="col">Author</th>
              <th scope="col">Price</th>
              <th scope="col">Pages</th>
              <th scope="col">Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr class="align-middle">
                <td>
                  <i class="bi bi-book"></i>
                </td>
                <td>
                  <strong><%= book.title %></strong>
                </td>
                <td><%= get_field(book, 'author') %></td>
                <td><%= number_to_currency(book.price) %></td>
                <td><%= get_field(book, 'pages') %></td>
                <td>
                  <%= link_to("View Book", book, class: "btn btn-primary") %>
                </td>
              </tr>
            <% end %>
        </table>
      </div>
    <% else %>
      <p>There are no books yet.</p>
    <% end %>

    <div>
      <%= link_to("New book", new_book_path, class: "btn btn-success") %>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render("breadcrumb", breadcrumbs: [
  { name: "Books", path: root_path },
  { name: "New Book" }
]) %>

<div class="card">
  <div class="card-body">
    <%= render("form", book: @book) %>
  </div>
</div>

app/views/books/show.html.erb
<h1>Book</h1>

<%= render("breadcrumb", breadcrumbs: [
  { name: "Books", path: root_path },
  { name: @book.title },
]) %>

<% content_for :alert_content do %>
  <% notice %>
<% end %>

<%= render("alert") %>

<div class="card">
  <div class="card-body">
    <%= render(@book) %>

    <div class="d-flex flex-row gap-3 mt-3">
        <%= link_to("Edit", edit_book_path(@book), class: "btn btn-primary") %>
        <%= link_to("Delete", delete_book_path(@book), method: :delete, class: "btn btn-danger") %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book Manager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container mt-5">
      <%= yield %>
    </div>
  </body>
</html>